name: Feature Request ✨
description: 建议一个新功能或改进
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您的功能建议！新的想法让 EchoAgent 变得更好。

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 在提交之前，请确认以下事项
      options:
        - label: 我已经搜索了现有的 Issues，确认这不是重复的功能请求
          required: true
        - label: 我已经查看了项目的 ToDo.md 文件
          required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 问题描述
      description: 描述您遇到的问题或需求
      placeholder: 当我使用 EchoAgent 时，我遇到了...
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: 建议的解决方案
      description: 描述您希望看到的功能或改进
      placeholder: 我希望能够...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 描述您考虑过的其他解决方案或功能
      placeholder: 我也考虑过...

  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型
      description: 这个功能属于哪个类别？
      options:
        - 新工具 (New Tool)
        - LLM 支持 (LLM Support)
        - UI/UX 改进 (UI/UX Improvement)
        - 性能优化 (Performance)
        - 安全性 (Security)
        - 文档 (Documentation)
        - 其他 (Other)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个功能的优先级如何？
      options:
        - 低 (Low)
        - 中 (Medium)
        - 高 (High)
        - 紧急 (Critical)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 使用场景
      description: 详细描述这个功能的使用场景
      placeholder: |
        用户场景：
        1. 作为一个 XXX 用户
        2. 我希望能够 XXX
        3. 这样我就可以 XXX
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: 实现思路
      description: 如果您有实现的想法，请分享
      placeholder: |
        可能的实现方式：
        - 在 tools_agent/ 下添加新工具
        - 修改 agent_frame.py 的逻辑
        - 等等...

  - type: textarea
    id: additional-context
    attributes:
      label: 额外信息
      description: 添加任何其他相关信息，如截图、链接、参考资料等
      placeholder: 任何其他有用的信息...
